### ISSUE TITLE
Error: no such global element: __lunatic_abort

### ISSUE THREAD

**Issue by shimaore** [lunatic-solutions/as-lunatic#12]
I might be doing this wrong, but (in an empty directory):
```
yarn add -D assemblyscript as-lunatic
echo '{"extends":"as-lunatic/asconfig.json"}' > asconfig.json
echo 'export function _start(): void {}' > server.ts
yarn exec asc server.ts
```
generates the error
```
[…]
▌ Error: no such global element: __lunatic_abort
▌     at E.initialize (/srv/home/stephane/Documents/Local/tmp/node_modules/assemblyscript/dist/assemblyscript.js:7:597337)
```

In case this matters (which would be weird since we're only compiling), I did not install `lunatic` locally.

**Comment by shimaore** [comment]
This is with assemblyscript@0.18.31 & as-lunatic@0.0.3, Node.js 16.1.0.

**Comment by shimaore** [comment]
Apparently a workaround is
```
import * as lib from 'lib';
```
although (based on the module's documentation) I suppose this was not what was intended :)

**Comment by jtenner** [comment]
I haven't experienced this issue. Fascinating. I'll take a look at this soon.

**Comment by jtenner** [comment]
Will look at this today.

**Comment by jtenner** [comment]
@bkolobara We might be able to get around the namespace problem and solve some of these issues by switching to a regular library instead of a lib.

```ts
import { Channel, Process } from "as-lunatic";
```

I also think that it might fix a types issue I've been trying to solve.

**Comment by bkolobara** [comment]
I think that it makes sense to switch.

**Comment by jtenner** [comment]
@bkolobara  and @shimaore I believe the current pull request solves this issue. Perhaps try it out locally?

**Comment by shimaore** [comment]
@jtenner in the project I was working on (which is a little bit more involved than the minimal example I provided at the start of this ticket), I am now getting errors along the lines of:
```
ERROR TS6054: File '~lib/channel.ts' not found.

 import * as channel from "channel";
                          ~~~~~~~~~
 in assembly/server.ts(3,26)
```

Note: I've tried with (a) plain `remove-lib` branch, and (b) `remove-lib` branch rebased on current master.

Getting back to the four-line example I provided at the start of this issue, I'm first getting a missing dependency (`Error: Cannot find module '@ason/transform'`) — then if I install that package I still get `▌ Error: no such global element: __lunatic_abort`.

**Comment by jtenner** [comment]
Yes. You want to

```ts
import { Channel } from "as-lunatic";
```

**Comment by jtenner** [comment]
Yes. You need to install @ason/transform . Otherwise channels and processes won't work. Just to be clear, it's installed behind the scenes when you install as-lunatic and extend the asconfig provided using the example.

**Comment by jtenner** [comment]
Hey! Thought I would check in on this. This problem should go away now. All you have to do is import as-lunatic.

```ts
import { } from "as-lunatic";
```
